# GitHub dependabot dependency management configuration file

version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly

    ignore:
      - dependency-name: string-strip-html
        update-types:
          - 'version-update:semver-major'