title: SimpleID
description: 'SimpleID is a simple, personal OpenID provider written in PHP.'
url: https://simpleid.org
# baseurl:

github:
    owner_url: https://github.com/simpleid
    repository_url: https://github.com/simpleid/simpleid.github.io

sourceforge:
    project_url: http://sourceforge.net/projects/simpleid
    group_id: 203264
