var TREE_ITEMS = [
['TOP', './index.html', ['cache', 'cache/index.html']
, ['extensions', 'extensions/index.html', ['hooks.php', 'extensions/hooks.php.html']
]
, ['identities', 'identities/index.html', ['example.identity.dist', 'identities/example.identity.dist.html']
]
, ['store', 'store/index.html']
, ['www', 'www/index.html', ['extensions', 'www/extensions/index.html', ['ax', 'www/extensions/ax/index.html', ['ax.extension.php', 'www/extensions/ax/ax.extension.php.html']
, ['ax.xtpl', 'www/extensions/ax/ax.xtpl.html']
]
, ['certauth', 'www/extensions/certauth/index.html', ['certauth.extension.php', 'www/extensions/certauth/certauth.extension.php.html']
]
, ['pape', 'www/extensions/pape/index.html', ['pape.extension.php', 'www/extensions/pape/pape.extension.php.html']
]
, ['sreg', 'www/extensions/sreg/index.html', ['sreg.extension.php', 'www/extensions/sreg/sreg.extension.php.html']
, ['sreg.xtpl', 'www/extensions/sreg/sreg.xtpl.html']
]
, ['ui', 'www/extensions/ui/index.html', ['ui.css', 'www/extensions/ui/ui.css.html']
, ['ui.extension.php', 'www/extensions/ui/ui.extension.php.html']
, ['ui.js', 'www/extensions/ui/ui.js.html']
]
]
, ['html', 'www/html/index.html', ['block.xtpl', 'www/html/block.xtpl.html']
, ['openid-consent.js', 'www/html/openid-consent.js.html']
, ['page-profile.js', 'www/html/page-profile.js.html']
, ['simpleid.css', 'www/html/simpleid.css.html']
, ['template.xtpl', 'www/html/template.xtpl.html']
, ['upgrade.css', 'www/html/upgrade.css.html']
, ['user-login.js', 'www/html/user-login.js.html']
]
, ['lib', 'www/lib/index.html', ['gettext', 'www/lib/gettext/index.html', ['gettext.inc', 'www/lib/gettext/gettext.inc.html']
, ['gettext.php', 'www/lib/gettext/gettext.php.html']
, ['streams.php', 'www/lib/gettext/streams.php.html']
]
, ['xtemplate.class.php', 'www/lib/xtemplate.class.php.html']
]
, ['locale', 'www/locale/index.html', ['messages.pot', 'www/locale/messages.pot.html']
]
, ['bignum.inc.php', 'www/bignum.inc.php.html']
, ['cache.inc.php', 'www/cache.inc.php.html']
, ['common.inc.php', 'www/common.inc.php.html']
, ['config.default.php', 'www/config.default.php.html']
, ['config.pear.php', 'www/config.pear.php.html']
, ['config.php.dist', 'www/config.php.dist.html']
, ['discovery.inc.php', 'www/discovery.inc.php.html']
, ['filesystem.store.php', 'www/filesystem.store.php.html']
, ['http.inc.php', 'www/http.inc.php.html']
, ['index.php', 'www/index.php.html']
, ['locale.inc.php', 'www/locale.inc.php.html']
, ['log.inc.php', 'www/log.inc.php.html']
, ['openid.inc.php', 'www/openid.inc.php.html']
, ['page.inc.php', 'www/page.inc.php.html']
, ['random.inc.php', 'www/random.inc.php.html']
, ['simpleweb.inc.php', 'www/simpleweb.inc.php.html']
, ['upgrade.php', 'www/upgrade.php.html']
, ['user.inc.php', 'www/user.inc.php.html']
, ['version.inc.php', 'www/version.inc.php.html']
]
, ['CHANGELOG.txt', 'CHANGELOG.txt.html']
, ['COPYING-xtemplate.txt', 'COPYING-xtemplate.txt.html']
, ['COPYING.txt', 'COPYING.txt.html']
, ['README.txt', 'README.txt.html']
, ['UPGRADE.txt', 'UPGRADE.txt.html']
, ['build.xml', 'build.xml.html']
, ['simpleid.properties', 'simpleid.properties.html']
]
];
