var TREE_ITEMS = [
['TOP', './index.html', ['cache', 'cache/index.html']
, ['extensions', 'extensions/index.html', ['hooks.php', 'extensions/hooks.php.html']
]
, ['identities', 'identities/index.html']
, ['store', 'store/index.html']
, ['www', 'www/index.html', ['extensions', 'www/extensions/index.html', ['ax', 'www/extensions/ax/index.html', ['ax.extension.php', 'www/extensions/ax/ax.extension.php.html']
]
, ['certauth', 'www/extensions/certauth/index.html', ['certauth.extension.php', 'www/extensions/certauth/certauth.extension.php.html']
]
, ['pape', 'www/extensions/pape/index.html', ['pape.extension.php', 'www/extensions/pape/pape.extension.php.html']
]
, ['sreg', 'www/extensions/sreg/index.html', ['sreg.extension.php', 'www/extensions/sreg/sreg.extension.php.html']
]
, ['ui', 'www/extensions/ui/index.html', ['ui.extension.php', 'www/extensions/ui/ui.extension.php.html']
]
]
, ['html', 'www/html/index.html']
, ['lib', 'www/lib/index.html', ['gettext', 'www/lib/gettext/index.html', ['gettext.inc.php', 'www/lib/gettext/gettext.inc.php.html']
, ['gettext.php', 'www/lib/gettext/gettext.php.html']
, ['streams.php', 'www/lib/gettext/streams.php.html']
]
, ['xtemplate.class.php', 'www/lib/xtemplate.class.php.html']
]
, ['locale', 'www/locale/index.html']
, ['bignum.inc.php', 'www/bignum.inc.php.html']
, ['cache.inc.php', 'www/cache.inc.php.html']
, ['common.inc.php', 'www/common.inc.php.html']
, ['config.default.php', 'www/config.default.php.html']
, ['config.pear.php', 'www/config.pear.php.html']
, ['discovery.inc.php', 'www/discovery.inc.php.html']
, ['filesystem.store.php', 'www/filesystem.store.php.html']
, ['http.inc.php', 'www/http.inc.php.html']
, ['index.php', 'www/index.php.html']
, ['locale.inc.php', 'www/locale.inc.php.html']
, ['log.inc.php', 'www/log.inc.php.html']
, ['openid.inc.php', 'www/openid.inc.php.html']
, ['page.inc.php', 'www/page.inc.php.html']
, ['random.inc.php', 'www/random.inc.php.html']
, ['simpleweb.inc.php', 'www/simpleweb.inc.php.html']
, ['upgrade.php', 'www/upgrade.php.html']
, ['user.inc.php', 'www/user.inc.php.html']
, ['version.inc.php', 'www/version.inc.php.html']
]
]
];
