name: Test build

on:
  push:
    branches-ignore:
      - 'features/11ty'
      - 'gh-pages'
      - 'prod'
  pull_request:
    branches-ignore:
      - 'features/11ty'
      - 'gh-pages'
      - 'prod'

jobs:
  github-pages:
    runs-on: ubuntu-latest
    env:
      PAGES_REPO_NWO: simpleid/simpleid.github.io
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: "${{ runner.os }}-gems-"

      - name: Run Jekyll build
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          build_only: true

