name: Test build

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PAGES_REPO_NWO: simpleid/simpleid.github.io
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Eleventy build
        run: npm run-script build
